# fly.toml app configuration file generated for ess-server on 2024-09-14T15:45:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ess-server'
primary_region = 'cdg'

[build]
[build.args]
GO_VERSION = '1.22.0'

[env]
PORT = '6080'

[http_service]
internal_port = 6080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[scale]
count = 1
